# Generated by Django 5.2.1 on 2025-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
                ('exam', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
